### ISSUE TITLE
PortChecker test seems to break in out of tree builds

### ISSUE THREAD

**Issue by dvzrv** [zynaddsubfx/zynaddsubfx#173]
Hi! When working on the package for 3.0.6 and the CI integration for Arch Linux, I noticed that the `PortChecker` test started failing.

I believe this is due to building out of tree (i.e. build directory is not in project directory).
The test should not fail on this not uncommon scenario.

**Comment by JohannesLorenz** [comment]
Reproduced with current zyn's master on 1 Arch Linux machine *sometimes*, but it always works with onther Arch linux machine. On one of my machines, it builds fine if the build directory is 1 level under the source tree, but fails *sometimes* in all other cases (i.e. 2 levels beneath, or in `/tmp`). The only thing I observe currently is that zyn does not reply anything at all.

It's a really strange issue. If a relative path would be wrong, then it would fail on both Arch Linux machines always.

@dvzrv I just pushed a fix on current master (that uses the MIDI dummy engine) that *might* fix the issue. Can you please re-try?

**Comment by dvzrv** [comment]
I guess you are referring to https://github.com/zynaddsubfx/zynaddsubfx/commit/6e25116ee8dded8d5ebd22fc5d8ef922fae11265?

That did not fix the issue unfortunately.

**Comment by JohannesLorenz** [comment]
> I guess you are referring to [6e25116](https://github.com/zynaddsubfx/zynaddsubfx/commit/6e25116ee8dded8d5ebd22fc5d8ef922fae11265)?

Yes, I mean that one. Hmm, I need to continue debugging it.
